server:
  port: 8001
  error:
    include-stacktrace: on_param

spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

#spring.application.name=hr-worker
#server.port=8001
#
## Database configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.defer-datasource-initialization=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console